server.port: 8090

spring:
  jpa.defer-datasource-initialization: true
  sql.init.mode: always
  datasource.url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"

security.remember.me.key: "my-secret"
